module.exports = {
    classes: {
        fifth_a: "5А",
        fifth_b: "5Б",
        fifth_v: "5В",
        sixth_a: "6А",
        sixth_b: "6Б",
        sixth_v: "6В",
        seventh_a: "7А",
        seventh_b: "7Б",
        seventh_v: "7В",
        eighth_a: "8А",
        eighth_b: "8Б",
        eighth_v: "8В",
        ninth_a: "9А",
        ninth_b: "9Б",
        ninth_v: "9В",
        tenth_a: "10А",
        tenth_b: "10Б",
        eleventh_a: "11А",
        eleventh_b: "11Б"
    },
    day_of_the_week_for_5a: {
        monday_5a: "Понедельник",
        tuesday_5a: "Вторник",
        wednesday_5a: "Среда",
        thursday_5a: "Четверг",
        friday_5a: "Пятница",
    },
    day_of_the_week_for_5b: {
        monday_5b: "Понедельник",
        tuesday_5b: "Вторник",
        wednesday_5b: "Среда",
        thursday_5b: "Четверг",
        friday_5b: "Пятница",
    },
    day_of_the_week_for_5v: {
        monday_5v: "Понедельник",
        tuesday_5v: "Вторник",
        wednesday_5v: "Среда",
        thursday_5v: "Четверг",
        friday_5v: "Пятница",
    },
    day_of_the_week_for_6a: {
        monday_6a: "Понедельник",
        tuesday_6a: "Вторник",
        wednesday_6a: "Среда",
        thursday_6a: "Четверг",
        friday_6a: "Пятница",
    },
    day_of_the_week_for_6b: {
        monday_6b: "Понедельник",
        tuesday_6b: "Вторник",
        wednesday_6b: "Среда",
        thursday_6b: "Четверг",
        friday_6b: "Пятница",
    },
    day_of_the_week_for_6v: {
        monday_6v: "Понедельник",
        tuesday_6v: "Вторник",
        wednesday_6v: "Среда",
        thursday_6v: "Четверг",
        friday_6v: "Пятница",
    },
    day_of_the_week_for_7a: {
        monday_7a: "Понедельник",
        tuesday_7a: "Вторник",
        wednesday_7a: "Среда",
        thursday_7a: "Четверг",
        friday_7a: "Пятница",
    },
    day_of_the_week_for_7b: {
        monday_7b: "Понедельник",
        tuesday_7b: "Вторник",
        wednesday_7b: "Среда",
        thursday_7b: "Четверг",
        friday_7b: "Пятница",
    },
    day_of_the_week_for_7v: {
        monday_7v: "[eq]",
        tuesday_7v: "Вторниgbcmrfк",
        wednesday_7v: "dlslvs",
        thursday_7v: "Четвrwfvwefwefерг",
        friday_7v: "///////",
    },
    day_of_the_week_for_8a: {
        monday_8a: "Понедельник",
        tuesday_8a: "Вторник",
        wednesday_8a: "Среда",
        thursday_8a: "Четверг",
        friday_8a: "Пятница",
    },
    day_of_the_week_for_8b: {
        monday_8b: "Понедельник",
        tuesday_8b: "Вторник",
        wednesday_8b: "Среда",
        thursday_8b: "Четверг",
        friday_8b: "Пятница",
    },
    day_of_the_week_for_8v: {
        monday_8v: "Понедельник",
        tuesday_8v: "Вторник",
        wednesday_8v: "Среда",
        thursday_8v: "Четверг",
        friday_8v: "Пятница",
    },
    day_of_the_week_for_9a: {
        monday_9a: "Понедельник",
        tuesday_9a: "Вторник",
        wednesday_9a: "Среда",
        thursday_9a: "Четверг",
        friday_9a: "Пятница",
    },
    day_of_the_week_for_9b: {
        monday_9b: "Понедельник",
        tuesday_9b: "Вторник",
        wednesday_9b: "Среда",
        thursday_9b: "Четверг",
        friday_9b: "Пятница",
    },
    day_of_the_week_for_9v: {
        monday_9v: "Понедельник",
        tuesday_9v: "Вторник",
        wednesday_9v: "Среда",
        thursday_9v: "Четверг",
        friday_9v: "Пятница",
    },
    day_of_the_week_for_10a: {
        monday_10a: "Понедельник",
        tuesday_10a: "Вторник",
        wednesday_10a: "Среда",
        thursday_10a: "Четверг",
        friday_10a: "Пятница",
    },
    day_of_the_week_for_10b: {
        monday_10b: "Понедельник",
        tuesday_10b: "Вторник",
        wednesday_10b: "Среда",
        thursday_10b: "Четверг",
        friday_10b: "Пятница",
    },
    day_of_the_week_for_11a: {
        monday_11a: "Понедельник",
        tuesday_11a: "Вторник",
        wednesday_11a: "Среда",
        thursday_11a: "Четверг",
        friday_11a: "Пятница",
    },
    day_of_the_week_for_11b: {
        monday_11b: "Понедельник",
        tuesday_11b: "Вторник",
        wednesday_11b: "Среда",
        thursday_11b: "Четверг",
        friday_11b: "Пятница",
    },
    class_word: {
        a: "А",
        b: "Б",
        v: "В"
    },
    back: "⬅ Назад",
};
